mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    random = models.IntegerField(default=0)
    count = models.IntegerField(default=0)
    sum = models.IntegerField(default=0)
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    max = models.IntegerField(default=-1)
    min = models.IntegerField(default=10000)
    sum = models.IntegerField(default=0)
    percent = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text



		
    
    

polls/forms.py
from django import forms
class UserForm(forms.Form):
    Назва_категорії = forms.CharField(max_length=100)
    Новий_кандидат_1= forms.CharField(max_length=100)
    Новий_кандидат_2= forms.CharField(max_length=100)
    Новий_кандидат_3= forms.CharField(max_length=100)
    Новий_кандидат_4= forms.CharField(max_length=100)
    Новий_кандидат_5= forms.CharField(max_length=100)
    

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from random import randint
from .models import Choice, Question
from django.utils import timezone
from .forms import UserForm

class IndexView(generic.ListView):
    model = Question
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        allQ=Question.objects.all()
        count = 0
        random = randint(4, 5)
        q1 = Question.objects.get(pk=4)
        for q in allQ:
            q.random=0
            q.save()
            count+=1
        q1.random = random
        q1.count = count
        q1.save()
        return Question.objects.all()

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):        
    question = get_object_or_404(Question, pk=question_id)
    allQ=Question.objects.all()
    allC=Choice.objects.all() 
    a = []
    max=-1
    min=10000
    sum=0
    try:
        all_choices = question.choice_set.all()
        selected_choice = question.choice_set.get(pk=request.POST['choice'])                 
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/results.html', {
            'question': question,
            'error_message': "Ви не вибрали кандидата",
        })
    else:  
        selected_choice.max = max
        selected_choice.min = min
        selected_choice.votes += 1
        selected_choice.sum = sum
        selected_choice.save()
       
        for choice in all_choices:
            choice.sum = sum
            choice.max = max
            choice.min = min
            a.append(choice.votes)
            a.append(selected_choice.votes)
            choice.save() 
        for i in a:
            if max<i:
                max=i
        for i in a:
            if min>i:
                min=i
        for choice in all_choices:
            sum+=choice.votes
            if choice.votes==max:
                choice.max = max
            if selected_choice.votes==max:
                selected_choice.max = max
            if choice.votes==min:
                choice.min = min
            if selected_choice.votes==min:
                selected_choice.min = min
            choice.save() 
            selected_choice.save()
        #Усього голосів:        
        selected_choice.sum = sum
        selected_choice.save()
        for choice in all_choices:
            choice.sum=sum
            choice.save()
        for choice in all_choices:
            choice.percent = (choice.votes * 100) / sum
            choice.save()
        sum=0
        for c in allC:
            sum+=c.votes    
        for q in allQ:
            q.sum=sum
            q.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def create(request):
    submitbutton=request.POST.get("submit")
    
    newQuestion=''
    newCandidate1=''
    newCandidate2=''
    newCandidate3=''
    newCandidate4=''
    newCandidate5=''
    if request.method == 'POST':
        form= UserForm(request.POST or None)
        
        if form.is_valid():
            newQuestion= form.cleaned_data.get("Назва_категорії")
            newCandidate1= form.cleaned_data.get("Новий_кандидат_1")
            newCandidate2= form.cleaned_data.get("Новий_кандидат_2")
            newCandidate3= form.cleaned_data.get("Новий_кандидат_3")
            newCandidate4= form.cleaned_data.get("Новий_кандидат_4")
            newCandidate5= form.cleaned_data.get("Новий_кандидат_5")
        if submitbutton != None:        
            newQ=Question(question_text=newQuestion, pub_date=timezone.now())
            newQ.save()
            newC1=newQ.choice_set.create(choice_text=newCandidate1)
            newC2=newQ.choice_set.create(choice_text=newCandidate2)
            newC3=newQ.choice_set.create(choice_text=newCandidate3)
            newC4=newQ.choice_set.create(choice_text=newCandidate4)
            newC5=newQ.choice_set.create(choice_text=newCandidate5)
            newC1.save()
            newC2.save()
            newC3.save()
            newC4.save()
            newC5.save()
        return redirect(request.path)
    else:   
        form= UserForm(request.POST or None)
        
        context= {'form': form, 'Назва_категорії': newQuestion,
                'Новий_кандидат_1':newCandidate1, 'Новий_кандидат_2':newCandidate2, 
                'Новий_кандидат_3':newCandidate3, 'Новий_кандидат_4':newCandidate4, 
                'Новий_кандидат_5':newCandidate5, 
                'submitbutton': submitbutton,
                }
        return render(request, 'polls/new.html', context)

polls/templates/polls/create.html
<!DOCTYPE html>
<html>
<head>
	<title>Create page</title>
</head>
<body>
	<form action="{% url 'polls:new' %}" method="post">
{% csrf_token %}
    <label class="text" for="question">Номінація</label><br>
    <input class="text" type="text" name="qText" id="question" value="">

    <label class="text" for="question">Введіть ім'я кандидатів:</label><br>
    <input class="text" type="text" name="cText" id="choice" value="">
<input type="submit" value="Create">
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>Main page</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/style1.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
	
<div class="veryMain">
<header>
<div class="container">
<img src="{% static 'polls/images/k.png' %} ">
<nav>
<ul>
<li><a href="{% url 'polls:create' %}">Створити голосувалку</a></li>
<li><a href="">Авторизуватися</a></li>
</ul>
</nav>
</div>
</header>
<br><br>

<div id="Main">
<div id="main1">
	<h1> ХТО ОТРИМАЄ 👑 ?</h1><br><br>
	<h2>Обирай: </h2><br>
	{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li class="fire">
        <a class="qt" href="{% url 'polls:results' question.id %}"><strong> {{ question.question_text }}</strong></a>
        </li>
    {% endfor %}
    </ul>
{% endif %}
	</div>

<div id="main2">
	<br><br><br>
	<h1>На нашому сайті вже</h1>
	<br><br>
	<p class="p1">Створено </p>
	 {% for question in latest_question_list %}
			{% if question.count != 0 %}
        	<strong><p class="p1">{{question.count}}</p></strong>
        	{% endif %}
   	{% endfor %}
   	<p class="p1"> голосувалок </p>
	
	<br>
   	
	<p class="p2">Проголосувало </p>
	{% for question in latest_question_list %}
			{% if question.id == 4 %}
        	<h2 class="p2">{{question.sum}}</h2>
        	{% endif %}
   	{% endfor %}
   	<p class="p2"> людей </p>
	
</div>

<div id="main3">
	
	<h1>Не знаєш, де проголосувати? </h1>
	<br><br>
	<h2>Переходь на рандомну категорію: </h2>
	<br>
	
		{% for question in latest_question_list %}
			{% if question.random != 0 %}
        	<p class="fire">
        	<a class="qt" href="{% url 'polls:results' question.random %}"> <strong>КЛАЦ</strong></a>
        	</p>
        	{% endif %}
   		{% endfor %}
</div>
</div>

<br><br>

<footer>
	<div class="mini">
	<a class="social" href="#"><i class="fa fa-telegram"></i></a>
	<a class="social" href="#"><i class="fa fa-instagram"></i></a>
	<a class="social" href="#"><i class="fa fa-github"></i></a> </div>
	<p id="AK">Alina Kvashenko</p>
</footer>
</div>
<script type="text/javascript">
	preventDefault();
</script>
</body>
</html>

polls/templates/polls/new.html
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'polls/style3.css' %}">
	<meta charset="UTF-8">
	<title>User Information Form</title>
</head>
<body>
<div class="Main">
	<center><h2>Не знайшов цікавої голосувалки на сайті? <br><br> Не біда, створи власну!</h2></center>
	<br>
<div class="Form">
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p }}
<input id="submit" type="Submit" name="submit" value="Підтвердити"/>
</form>
</div>

{% if submitbutton == "Submit" %}
<h1>Ви створили категорію: {{ Назва_категорії }}</h1>
{% endif %}
<br>
<button> <a id="back" href="{% url 'polls:index' %}">Повернутися на головну сторінку</a> </button>
</div>
</body>
<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) </script>
<script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script></html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>Results page</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/style2.css' %}">
</head>
<body>
<div class="Main">
<div class="left">
	<div class="data">
	<h1>{{ question.question_text }}</h1>
	</div>
	<br><br>

<div class="vote">
{% if error_message %}<p>Спочатку обери кандидата</p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label class="radio" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br>
<input class="back" type="submit" value="Голосувати">
</form>
</div>

<div class="all">
	<br><br><br>
<p class="p">У цій категорії вже проголосувало</p>
{% for choice in question.choice_set.all %}
		{% if choice.id == 6 or choice.id == 1 %}
		<h2 class="p">{{ choice.sum }} </h2>
	 	{% endif %}
	{% endfor %}
<p class="p">користувачів</p>
	
<br><br>
<a href="{% url 'polls:index' %}"><input type="button" class="back" value="Голосувати в іншій категорії" ></a>
</div>
</div>

<div class="right">
<div class="res">
{% for choice in question.choice_set.all %}
	<label class="bars" for="bar">{{ choice.choice_text }}: {{choice.votes}} голосів</label>
	<br>
	<progress class="bars" id="bar" value="{{ choice.percent }}" max="100"> {{ choice.percent }} </progress>
	<label class="bars" for="bar">{{ choice.percent }} %</label>
	<br>
{% endfor %}

<br><br>
</div>


	<div class="lilu">
	<div class="li">
<h2>Лідери голосування:</h2>

{% for choice in question.choice_set.all %}
		{% if choice.max > -1 %}
		<p class="top">{{ choice.choice_text }} - <strong>{{ choice.max }}</strong> прихильників </p>
	 	{% endif %}
{% endfor %}

<br><br>
	</div>

	<div class="lu">
<h2>Лузери голосування:</h2>

{% for choice in question.choice_set.all %}
		{% if choice.min != 10000 and choice.min != choice.max %}
		<p class="dno">{{ choice.choice_text }} - <strong>{{ choice.min }}</strong> прихильників </p>
		
	 	{% endif %}
{% endfor %}


<br><br>
	</div>

	</div>
</div>

</div>
</body>
</html>